In [33]:
import numpy as np
print=__builtins__.print
#exercice1
mon_tableau=np.arange(10)
print ("mon Tableau est :",mon_tableau)
#Exercice2
my_list=[3.14, 2.17, 0, 1, 2]
mon_tableau_2=np.array(my_list)
mon_tableau_2=mon_tableau_2.astype(int)
print ("mon tableau est :",mon_tableau_2)
#Exercice3
mon_tableau_3=np.array((np.arange(1,4),np.arange(4,7),np.arange(7,10)))
print ("mon tableau est :",mon_tableau_3)
#Exercice4
mon_tableau_aleatoire=(np.random.rand(4,5))
print ("mon tableau est :",mon_tableau_aleatoire)
#Exercice5
mon_tableau_5=np.array([[21, 22, 23, 22, 22],
                        [20, 21, 22, 23, 24],
                        [21, 22, 23, 22, 22]])
Deuxieme_ligne=mon_tableau_5[1]
print ("Deuxieme ligne est :",Deuxieme_ligne)
#Exercice6
mon_tableau_6=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
mon_tableau_6=mon_tableau_6[::-1]
print ("mon tableau est :",mon_tableau_6)
#Exercice7
Matrice_I=np.eye(4)
print("Matrice_I:",Matrice_I)
#Exercice8
mon_tableau_8=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
print ("la somme de mon tableau est =",np.sum(mon_tableau_8))
print ("la moyenne de mon tableau est =",np.mean(mon_tableau_8))
print ("la valeur max de mon tableau est =",np.max(mon_tableau_8))
print ("la valeur min de mon tableau est =",np.min(mon_tableau_8))
#Exercice9
mon_tableau_9=np.arange(1,21).reshape(4,5)
print ("mon tableau est :",mon_tableau_9)
#Exercice10
mon_tableau_10=np.arange(1,21)
mon_tableau_impaire=mon_tableau_10[mon_tableau_10%2!=0]
print ("mon tableau est :",mon_tableau_impaire)

mon Tableau est : [0 1 2 3 4 5 6 7 8 9]
mon tableau est : [3 2 0 1 2]
mon tableau est : [[1 2 3]
 [4 5 6]
 [7 8 9]]
mon tableau est : [[0.50045713 0.12184577 0.62566575 0.55387283 0.30830672]
 [0.81943    0.86167692 0.1097628  0.91526792 0.01558012]
 [0.81294955 0.10590065 0.97655877 0.62944404 0.24979228]
 [0.76170584 0.93441479 0.64347337 0.26565437 0.61524111]]
Deuxieme ligne est : [20 21 22 23 24]
mon tableau est : [0 1 2 3 4 5 6 7 8 9]
Matrice_I: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
la somme de mon tableau est = 45
la moyenne de mon tableau est = 4.5
la valeur max de mon tableau est = 9
la valeur min de mon tableau est = 0
mon tableau est : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
mon tableau est : [ 1  3  5  7  9 11 13 15 17 19]
